---
- name: Deploy cluster with Kubespray
  import_playbook: submodules/kubespray/cluster.yml

- name: Kubernetes config file
  hosts: kube_control_plane[0]

  tasks:
  - name: Create .kube directory
    file:
      path: .kube
      state: directory

  - name: Copy admin.conf to .kube/config
    become: yes
    become_method: sudo
    copy:
      src: /etc/kubernetes/admin.conf
      dest: .kube/config
      remote_src: yes
      owner: "{{ ansible_effective_user_id | string }}"
      group: "{{ ansible_effective_group_id | string }}"

- include: add-nvidia-gpu-operator.yml
  when: nvidia_gpu_operator | default('false') | bool == true