---
- name: Deploy cluster with Kubespray
  import_playbook: submodules/kubespray/cluster.yml

- name: Kubernetes config file
  hosts: kube_control_plane[0]

  tasks:
  - name: Copy admin.conf to .kube/config
    become: yes
    become_method: sudo
    copy:
      src: /etc/kubernetes/admin.conf
      dest: .kube/config
      remote_src: yes
      owner: "{{ ansible_effective_user_id | string }}"
      group: "{{ ansible_effective_group_id | string }}"

- name: Install Nvidia GPU Operator
  hosts: kube_control_plane[0]
  roles:
    - nvidia-gpu-operator
  when: nvidia_gpu_operator_enabled | default('false') | bool == true